version: '3'

services:
    php:
        build:
            context: docker
            dockerfile: Dockerfile.php
        restart: unless-stopped
        networks:
            - php-network
            - db-network

    db:
        image: mariadb:10.5
        restart: unless-stopped
        networks:
            - db-network
        volumes:
            - ./data/db:/var/lib/mysql
            #- ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro

networks:
    db-network:
        driver: bridge
    php-network:
        driver: bridge
