version: '3'

services:
  php:
    volumes:
      - ./data/myexample:/var/www/myexample.localhost

  web_example:
    image: balrok_nginx
    restart: unless-stopped
    environment:
      - SERVERNAME=myexample.localhost
      - SERVERDIR=/var/www/myexample.localhost
      - TYPE=yii
    volumes:
      - ./data/myexample:/var/www/myexample.localhost
    ports:
      - "8080:80"
    networks:
      - php-network
